#Requires -Modules Pester

BeforeDiscovery {
    [System.Diagnostics.CodeAnalysis.SuppressMessage(
        'PSUseDeclaredVarsMoreThanAssignments',
        '',
        Scope = '*',
        Target = 'SuppressImportModule'
    )]
    $SuppressImportModule = $true
    . $PSScriptRoot\Shared.ps1
}

# based on work from https://github.com/juneb/PesterTDD/blob/master/Module.Help.Tests.ps1

Describe "Help for module $ModuleName" {
    ## When testing help, remember that help is cached at the beginning of each session.
    ## To test, restart session.

    BeforeDiscovery {
            # Workflow not supported on PS7
        $CommandList = foreach ($command in Get-Command -Module $ModuleName -CommandType Cmdlet, Function) {
            @{
                FullName    = '{0}\{1}' -f $ModuleName, $command.Name
                CommandName = $command.Name
            }
        }
    }

    Describe '<CommandName>' -ForEach $CommandList -AllowNullOrEmptyForEach -Tags @('MetaTest') {
        BeforeDiscovery {
            $help = Get-Help -Name $FullName -ErrorAction SilentlyContinue
        }

        It 'Should not be auto-generated' -TestCases @{ Synopsis = $help.Synopsis } {
            # If help is not found, synopsis in auto-generated help is the syntax diagram
            $Synopsis |
                Should-NotMatchString "\s*$CommandName" -Because 'Help should not be generated by help system'
        }

        It 'Has a synopsis' -TestCases @{ Synopsis = $help.Synopsis } {
            $Synopsis |
                Should-NotBeEmptyString -Because 'Command should have a synopsis'
        }

        It 'Has description' -TestCases @{ Description = $help.description } {
            $Description.Count |
                Should-BeGreaterThan 0 -Because 'Command should have a description'
            $Description.Text | Select-Object -First 1 |
                Should-NotBeEmptyString -Because 'Command description should not be empty'
        }

        Context 'Examples' {
            BeforeDiscovery {
                $Examples = foreach ($example in $help.Examples.example) {
                    @{
                        code    = $example.code
                        remarks = $example.remarks
                        title   = $example.title
                    }
                }
            }
            It '<CommandName> has at least one example' -ForEach @{ examples = $Examples } {
                $Examples.Count |
                    Should-BeGreaterThan 0 -Because 'Every command should have an example'
            }

            Context '<title>' -ForEach $Examples -AllowNullOrEmptyForEach {
                It 'has code' {
                    $code | Should-NotBeEmptyString -Because 'Every example should have code block'
                }
                It 'has description' {
                    $remarks.Text | Select-Object -First 1 |
                        Should-NotBeEmptyString -Because 'Every example should be described'
                }
            }
        }

        Context 'Parameters' {
            BeforeDiscovery {
                $common = @(
                    [Management.Automation.PSCmdlet]::CommonParameters
                    [Management.Automation.PSCmdlet]::OptionalCommonParameters
                )

                # Without the filter, WhatIf and Confirm parameters are still flagged in "finds help parameter in code" test
                $helpParameters = $help.parameters.parameter |
                    Where-Object Name -NotIn $common |
                    Sort-Object -Property Name -Unique
                $parameters = (Get-Command $FullName).ParameterSets.Parameters |
                    Where-Object Name -NotIn $common |
                    Sort-Object -Property Name -Unique

                $ParameterList = foreach ($parameter in $parameters) {
                    @{
                        parameterName = $parameter.Name
                        parameter     = $parameter
                        parameterHelp = $helpParameters | Where-Object Name -EQ $parameter.Name
                    }
                }
            }

            It 'All parameters have help topic' -ForEach @{
                helpParameters = $helpParameters
                parameters     = $parameters
            } {
                $Because = 'The number of parameters in the help should match the number in the command'
                @($helpParameters).Count |
                    Should -Be @($parameters).Count -Because $Because
            }

            Context 'Parameter <parameterName>' -ForEach $ParameterList -AllowNullOrEmptyForEach {
                It 'Has help description' {
                    $parameterHelp.Description.Count |
                        Should-BeGreaterThan 0 -Because 'Parameter should have a description'
                    $parameterHelp.Description[0].Text |
                        Should-NotBeEmptyString -Because 'Parameter description should not be empty'
                }

                It 'Has correct Mandatory value' {
                    $because = 'The parameter mandatory status in help should match the code'
                    $codeMandatory = $parameter.IsMandatory.toString()
                    $parameterHelp.Required | Should-Be $codeMandatory -Because $because
                }

                It 'Has correct parameter type' {
                    $because = 'The parameter type in help should match the code'
                    $codeType = $parameter.ParameterType.Name

                        # To avoid calling Trim method on a null object.
                    $helpType = if ($parameterHelp.parameterValue) { $parameterHelp.parameterValue.Trim() }
                    $helpType | Should-Be $codeType -Because $because
                }
            }
        }

        Context 'Help Links' {
            BeforeDiscovery {
                $links = $help.relatedLinks.navigationLink |
                    Where-Object uri |
                    ForEach-Object {
                        @{
                            linkText = $_.linkText
                            uri      = $_.uri
                        }
                    }
            }
            It 'Link is available online - <linkText>' -ForEach $links -AllowNullOrEmptyForEach {
                $Result = Invoke-WebRequest -Uri $uri -UseBasicParsing
                $Result.StatusCode |
                    Should -Be '200' -Because 'URL should respond'
            }
        }
    }
}
